/**
 * SFI RIT - AI Explanation Engine (Triple-Stack Reliability)
 * This version uses Environment Variables for security.
 */

const AI_CONFIG = {
    // Level 1: Google Gemini (Primary)
    GEMINI_KEY: import.meta.env.VITE_GEMINI_KEY || '',
    GEMINI_URL: 'https://generativelanguage.googleapis.com/v1/models/gemini-2.0-flash:generateContent',
    
    // Level 2: Groq (Secondary)
    GROQ_KEY: import.meta.env.VITE_GROQ_KEY || '',
    GROQ_URL: 'https://api.groq.com/openai/v1/chat/completions',
    GROQ_MODEL: 'llama-3.1-8b-instant',

    // Level 3: OpenRouter (Emergency Fallback)
    OR_KEY: import.meta.env.VITE_OR_KEY || '',
    OR_URL: 'https://openrouter.ai/api/v1/chat/completions',
    OR_MODEL: 'google/gemini-flash-1.5-8b'
};

/**
 * Fetches an AI-powered explanation with triple-layer failover
 */
export async function fetchAIExplanation(q, onComplete) {
    if (q.ai_explanation || q.is_fetching) return;
    q.is_fetching = true;

    // Safety check for keys
    if (!AI_CONFIG.GEMINI_KEY && !AI_CONFIG.GROQ_KEY && !AI_CONFIG.OR_KEY) {
        q.ai_explanation = "AI Error: API Keys are not configured. Please check your Environment Variables.";
        return finish();
    }

    const optionsList = q.options
        .map((opt, i) => `${String.fromCharCode(65 + i)}: ${opt}`)
        .filter(opt => opt && !opt.includes("undefined"))
        .join(', ');

    const prompt = `You are a professional KEAM entrance exam tutor. Explain this multiple choice question from the Entrance Exam in 2-3 simple, clear lines using simple language.
    
Question: ${q.text}
Options: ${optionsList}
Correct Answer: ${q.correct}

Provide only the explanation text. Focus strictly on the core concept. Limit to 3 sentences max.`;

    try {
        // --- Attempt 1: Gemini (Primary) ---
        if (AI_CONFIG.GEMINI_KEY) {
            const gRes = await fetch(`${AI_CONFIG.GEMINI_URL}?key=${AI_CONFIG.GEMINI_KEY}`, {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({
                    contents: [{ parts: [{ text: prompt }] }],
                    generationConfig: { temperature: 0.4, maxOutputTokens: 256 }
                })
            });
            const gData = await gRes.json();
            if (!gData.error && gData.candidates?.[0]?.content?.parts?.[0]?.text) {
                q.ai_explanation = gData.candidates[0].content.parts[0].text.trim();
                return finish();
            }
            console.warn("Gemini Failed. Progressing to backup...");
        }

        // --- Attempt 2: Groq (Secondary) ---
        if (AI_CONFIG.GROQ_KEY) {
            try {
                const groqRes = await fetch(AI_CONFIG.GROQ_URL, {
                    method: 'POST',
                    headers: { 'Authorization': `Bearer ${AI_CONFIG.GROQ_KEY}`, 'Content-Type': 'application/json' },
                    body: JSON.stringify({
                        model: AI_CONFIG.GROQ_MODEL,
                        messages: [{ role: "user", content: prompt }],
                        max_tokens: 300
                    })
                });
                const groqData = await groqRes.json();
                if (groqData.choices?.[0]?.message?.content) {
                    q.ai_explanation = groqData.choices[0].message.content.trim() + " (Generated by Backup Engine)";
                    return finish();
                }
            } catch(e) { console.error("Groq Network Error"); }
        }

        // --- Attempt 3: OpenRouter (Emergency) ---
        if (AI_CONFIG.OR_KEY) {
            try {
                const orRes = await fetch(AI_CONFIG.OR_URL, {
                    method: 'POST',
                    headers: {
                        'Authorization': `Bearer ${AI_CONFIG.OR_KEY}`,
                        'Content-Type': 'application/json'
                    },
                    body: JSON.stringify({
                        model: AI_CONFIG.OR_MODEL,
                        messages: [{ role: "user", content: prompt }]
                    })
                });
                const orData = await orRes.json();
                if (orData.choices?.[0]?.message?.content) {
                    q.ai_explanation = orData.choices[0].message.content.trim() + " (Generated by Emergency Engine)";
                    return finish();
                }
            } catch(e) { console.error("OpenRouter Network Error"); }
        }

        throw new Error("All AI layers failed.");

    } catch (e) {
        console.error("AI Triple-Stack Error:", e);
        q.ai_explanation = "The AI system is offline. Please check the solution logic manually.";
    } finally {
        finish();
    }

    function finish() {
        q.is_fetching = false;
        if (typeof onComplete === 'function') onComplete();
    }
}
